service: no-server-november
provider:
  name: aws
  deploymentBucket:
    name: com.ulfhedinn.${self:custom.region.${self:custom.stage}}.deploys
  runtime: nodejs8.10
  cfLogs: true
  logRetentionInDays: 90
  region: ${self:custom.region.${self:custom.stage}}
  stage: prod
  versionFunctions: false
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: Allow
      Action: # Credstash KMS key, for decrypting secrets (alias/credstash)
        - kms:Decrypt
        - kms:GenerateDataKey
      Resource: "arn:aws:kms:${self:provider.region}:*:key/b7754a99-7b1a-4b65-adda-7b4f8416836b"

package:
  exclude:
    - github-check.private-key.pem.ts

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  region:
    prod: us-west-2
  domain:
    prod: no-server-november.ulfhedinn.net
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

# resources: ${file(resources.yml)}

functions:
# =--= Lorem Ipsum =-------------------------------------------------------------------------------=
  lorem_ipsum:
    handler: functions/lorem_ipsum.handler
    events:
      - http:
          method: get
          path: lorem_ipsum

# =--= Dad Jokes Twitter =-------------------------------------------------------------------------=
  dadbot:
    handler: functions/dadbot.handler
    events:
      - schedule: rate(2 hours)

# =--= GitHub Check =------------------------------------------------------------------------------=
  github_check:
    handler: functions/github_check.handler
    events:
      - http:
          method: post
          path: github_check
    package:
      include:
        - github-check.private-key.pem.ts

# =--= Cat Memes =---------------------------------------------------------------------------------=
  cat_meme:
    handler: functions/cat_meme.handler
    events:
      - http:
          method: get
          path: cat_meme

# =--= One Direction =-----------------------------------------------------------------------------=
  one_direction:
    handler: functions/one_direction.handler
    events:
      - alexaSkill: amzn1.ask.skill.343bb68b-abc5-48e7-8507-4d7fee38c6f8

# =--= Image Classifier =--------------------------------------------------------------------------=
  image_classifier:
    timeout: 30
    handler: functions/imagebot.handler
    events:
      # The following events are only available to me, `serverless invoke local` tyvm
      # - http: # Tell the bot to register itself for web-hooks
      #     method: patch
      #     path: imagebot
      # - http: # Tell the bot to register itself for web-hooks
      #     method: delete
      #     path: imagebot
      - http: # CRC Challenge/Response to enable new web-hooks
          method: get
          path: imagebot
      - http: # Primary twitter event entrypoint
          method: post
          path: imagebot

# =--= Twilio Integration =------------------------------------------------------------------------=
  twilio_wakeup:
    handler: functions/twilio_wakeup.handler
    events:
      - cron(0 16 ? ? ? ?)


# =--= Slack Integration =-------------------------------------------------------------------------=
  actionbot:
    handler: functions/actionbot.handler
    events:
      - http:
          method: post
          path: actionbot
