service: no-server-november
provider:
  name: aws
  deploymentBucket:
    name: com.ulfhedinn.${self:custom.region.${self:custom.stage}}.deploys
  runtime: nodejs6.10
  cfLogs: true
  logRetentionInDays: 90
  region: ${self:custom.region.${self:custom.stage}}
  stage: prod
  versionFunctions: false
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
    - Effect: Allow
      Action: # Credstash KMS key, for decrypting secrets (alias/credstash)
        - kms:Decrypt
        - kms:GenerateDataKey
      Resource: "arn:aws:kms:${self:provider.region}:*:key/b7754a99-7b1a-4b65-adda-7b4f8416836b"

package:
  individually: true
  exclude:
    - github-check.private-key.pem.ts

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  region:
    prod: us-west-2
  webpack:
    includeModules: true
    forceExclude:
      - aws-sdk
  domain:
    prod: no-server-november.ulfhedinn.net

# resources: ${file(resources.yml)}

functions:
# =--= Lorem Ipsum =-------------------------------------------------------------------------------=
  lorem_ipsum:
    handler: functions/lorem_ipsum.handler
    events:
      - http:
          method: get
          path: lorem_ipsum

# =--= Dad Jokes Twitter =-------------------------------------------------------------------------=
  dadbot:
    handler: functions/dadbot.handler
    events:
      - schedule: rate(2 hours)

# =--= GitHub Check =------------------------------------------------------------------------------=
  github_check:
    handler: functions/github_check.handler
    events:
      - http:
          method: post
          path: github_check
    package:
      include:
        - github-check.private-key.pem.ts
