export const facts = [
  "Liam Payne was born on 29th August 1993. His star sign in Virgo.",
  "Niall Horan was born on 13th September 1993. Just like Liam, he’s a Virgo.",
  "Zayn Malik was born on 12th January 1993. He’s a Capricorn just like Louis.",
  "Harry Styles' musical heroes are The Beatles and he’s also a huge Coldplay fan.",
  "Harry was brought up in the village of Holmes Chapel in Cheshire.",
  "Harry’s favourite TV show is Family Guy and his favourite movie is Love Actually - however, he tells everyone it’s Fight Club to seem more manly!",
  "While on The X Factor, Harry had a big crush on judge Cheryl - who his bandmate Liam Payne went onto have a two-year relationship and a baby with - and The Xtra Factor host Caroline Flack, who he later reportedly dated. He’s joked that his man crush is bandmate Louis Tomlinson!",
  "Harry sleeps naked!",
  "Louis was brought up in Doncaster, South Yorkshire. Other famous people who hail from there include Jeremy Clarkson and Brian Blessed.",
  "If Louis had a superpower, he would fly.",
  "Louis’s favourite band is The Fray.",
  "Louis’s celebrity crush is Diana Vickers and his man crush is Robbie Williams.",
  "Liam Payne released his debut EP on the 24th August 2018.",
  "Liam spent his childhood in Wolverhampton, the birthplace of Led Zeppelin legend Robert Plant and Slade’s Noddy Holder.",
  "Liam’s favourite colour is purple.",
  "Liam also took part the 2008 series of The X Factor, making it through to the Judges' Houses round and visited Simon’s house in Barbados where he was cruelly eliminated.",
  "Liam’s favourite film is the Toy Story trilogy.",
  "Liam’s celebrity crush is Leona Lewis and his man crush is stand-up comedian Michael McIntyre.",
  "Liam only has one kidney after getting one removed as a kid. He’s completely teetotal and never touches a drop of alcohol, as he explains, “It’s just a choice to be on the safe side.”",
  "Liam once cried while watching Marley & Me. Bless.",
  "Liam has a very unusual phobia – SPOONS! He admits it’s “very strange” and would like to invent an ‘anti-spoons’ app for mobile phones.",
  "Niall’s ideal woman is Cheryl Cole - his bandmate Liam's now ex-girlfriend - and his man crush is Michael Bublé.",
  "Niall’s favourite movie of all time is Grease.",
  "Niall is left-handed.",
  "Niall was brought up in Mullingar in Ireland.",
  "On their 53:14 min long debut album ‘Up All Night’, Harry gets 7:18min worth of solos, Liam has 7:08min, Zayn has 5:38min, Louis has 1:29min and Niall has 1:24min.",
  "Zayn was brought up in Bradford, West Yorkshire. Other famous Bradfordians include the Brontë sisters, magician Dynamo and Gareth Gates.",
  "Zayn fancies the pants off Megan Fox and has a secret man crush on Justin Timberlake.",
  "Zayn’s favourite book is Harry Potter.",
  "Zayn says he has a soft spot for intelligent girls.",
  "Zayn can’t swim.",
  "Zayn’s favourite band of all time is *NSYNC.",
  "Zayn’s X Factor audition wasn’t broadcast on the main show. When he had progressed further it was retrospectively shown on spin-off show, The Xtra Factor.",
  "Niall sang Ne-Yo’s ‘So Sick’ in the X Factor first round and received glowing praise from Louis Walsh. A big Oasis fan, he later covered ‘Champagne Supernova’ at bootcamp.",
  "Liam sang ‘Cry Me A River’ in his 2010 audition and received a standing ovation. At bootcamp he covered Oasis’ ‘Stop Crying Your Heart Out.’",
  "Louis auditioned with Plain White T’s ‘Hey There Delilah’ and got a clean sweep of yes’s from the judges.",
  "Harry impressed two out of the three judges in The X Factor's first round with a version of Stevie Wonder’s ‘Isn’t She Lovely’. Louis Walsh had doubts but once progressed Harry sang ‘Stop Crying Your Heart Out’ at bootcamp.",
  "Niall’s favourite colour is blue.",
  "One Direction are the brand ambassadors for the computer game Pokémon Black and White and have appeared on TV adverts and performed at events.",
  "The band’s Twitter ID’s are @Harry_Styles, @NiallOfficial, @zaynmalik, @LiamPayne and @Louis_Tomlinson.",
  "Niall has the most Twitter followers with 39.3 million.",
  "It was guest judge, former Pussycat Doll Nicole Scherzinger, who suggested that Harry, Niall, Zayn, Liam and Louis should be put together as a group at The X Factor bootcamp.",
  "One Direction finished third on The X Factor behind winner Matt Cardle and runner-up Rebecca Ferguson.",
  "Harry came up with the band name One Direction.",
  "After coming third on The X Factor, One Direction were snapped up by Simon Cowell’s record label Syco.",
  "1D’s debut single ‘What Makes You Beautiful’ entered the UK chart at Number 1 selling a whopping 153,965 copies in its first week. It also smashed the pre-order sales record at One Direction’s label Sony Music.",
  "One Direction’s 2011/2012 UK tour sold out in just 12 minutes when tickets went on sale.",
  "Before auditioning for The X Factor, Harry was the frontman of the band White Eskimo which featured his school friends Haydn Morris, Nick Clough and Will Sweeney.",
  "The ‘One Direction 2012 Calendar’ is the best-selling calendar of all time on Amazon.co.uk ahead of Cheryl Cole and JLS’s official 2011 calendars.",
  "Liam is an avid fan of boxing.",
  "Niall says he’s only read one book – the American classic ‘To Kill A Mockingbird’.",
  "One Direction albums are known to top the charts – their debut album ‘Up All Night’ was the 16th biggest-selling album of 2011 in the UK, shifting 468,000 copies.",
  "1D’s second single ‘Gotta Be You’ was released on 13th November 2011 and reached number three on the UK chart.",
  "Despite not hitting the top spot, ‘Up All Night’ was the highest-selling Number 2 album of 2011 with 138,163 copies sold in the first week alone.",
  "‘Up All Night’ also charted in the top ten in Ireland, Sweden, Belgium, Holland, New Zealand and Australia.",
  "1D’s debut tour of North America will see the boys support US band Big Time Rush. They’ll play ten shows kicking off at Chicago Rosemont Theatre on 24th February 2012.",
  "‘What Makes You Beautiful’ won the Best British Single at the 2012 Brit Awards.",
  "1D took part in The X Factor Live Tour from February to April 2011.",
  "Had One Direction won The X Factor, they would have released a cover of the 1984 synthpop anthem ‘Forever Young’ by German group Alphaville. 1D’s version leaked onto the internet soon after The X Factor was finished.",
  "‘Up All Night’ was recorded in three separate places – London, Los Angeles and Sweden.",
  "Ed Sheeran and American Idol winner Kelly Clarkson both penned tracks for ‘Up All Night’.",
  "Niall, Liam, Louis, Zayn and Harry co-wrote four songs on the record – ‘Taken’, ‘Everything About You’, ‘Same Mistakes’ and ‘Save You Tonight’.",
  "‘Up All Night’ sold 1,086,434 copies in the UK and has been certified 3x Platinum by the British Phonographic Industry.",
  "‘Up All Night’ was released in the US and Canada on 20th March 2012 on Columbia Records.",
  "Along with fellow former contestants JLS, 1D guested on the 2011 The X Factor finalists single ‘Wishing On A Star’ in November 2011. It charted at Number 1 with first-week sales of 98,932.",
  "1D’s third single ‘One Thing’ was released digitally on 6th January 2012 and reached number 28 on the chart.",
  "Zayn’s name is actually spelt with an ‘i’ (Zain). He reckons ‘Zayn’ is more original and adopted it as his stage name.",
  "Niall has a very bizarre good luck mascot – a pair of white socks.",
  "Liam once confessed to owning a pair of pink hair straighteners. Nice!",
  "The ‘Gotta Be You’ video was filmed in New York and on the banks of Lake Placid.",
  "Harry’s favourite song of all time is ‘Free Falling’ by John Mayer.",
  "Zayn, Louis and Harry all support Manchester United. Liam is a West Bromwich Albion fan while Niall follows Derby County.",
  "Niall is an accomplished guitar player while Harry plays the kazoo!",
  "Simon Cowell believed that the band had what it takes to become one of the biggest boy bands on the planet, telling the Daily Star, \"I think they are the new Take That.\"",
  "The ‘One Thing’ music video was shot at various locations in London on 28th November 2011 and premiered on YouTube 13th January 2012.",
  "To date ‘What Makes You Beautiful’, ‘Gotta Be You’ and ‘One Thing’ have amassed over 70million views altogether on YouTube. Impressive!",
  "During The X Factor auditions, all the 1D boys were students. Niall was at Colaiste Mhuire secondary school in Millingar, Zayn studied at Tong High School in Bradford, Liam was at the City of Wolverhampton College, Harry was a pupil at Holmes Chapel Comprehensive School and Louis was a sixth former at Hall Cross School in Doncaster.",
  "Zayn dated fellow X Factor star Rebecca Ferguson for four months but the relationship ended when they “drifted apart”. Rebecca is six years older than Zayn.",
  "The One Direction dolls are all 30cm in height and were created using laser-image face-sculpts for maximum authenticity.",
  "Harry makes a brief cameo appearance in Ed Sheeran’s first ‘Drunk’ video. It was filmed backstage at London’s Shepherd’s Bush Empire.",
  "Harry says he would happily date a fan! When asked, he said, “Yeah definitely, because if you like someone, you like someone. If they’re a fan it shouldn’t make any difference.”",
  "Harry’s ex-girlfriend Caroline Flack was 15 years his senior. During their relationship, he was 17-years-old and she was 32-years-old.",
  "Contrary to media reports that Harry ‘dumped’ Caroline Flack, he insists that the pair ended things amicably. He tweeted, “Please know I didn't 'dump' Caroline. This was a mutual decision. She is one of the kindest, sweetest people I know. Please respect that.”",
  "1D’s first book 'One Direction: Forever Young (Our Official X Factor Story)’ debuted at number one on the Sunday Times Bestseller list.",
  "Harry has a sister called Gemma.",
  "Zayn has three sisters but no brothers. They’re called Doniya, Waliyha and Safaa.",
  "Niall has an older brother called Greg. He’s 23.",
  "Louis has five sisters. They’re called Lottie, Fizz, Daisy, Phoebe and Georgia.",
  "Liam and Niall both share the same middle name – James.",
  "Louis’s middle name is William, Harry’s is Edward and Zayn’s is Jawaad.",
  "Liam started dated One Direction backing dancer Danielle Peazer in December 2010.",
  "Harry hasn’t always wanted to be a singer. Before he took part in The X Factor, he had ambitions to be a lawyer!",
  "One Direction had a bizarre pre-gig ritual of earing Haribo sweets together.",
  "Zayn’s favourite song is ‘Thriller’ by Michael Jackson, Harry loves ‘Shine On You Crazy Diamond’ by Pink Floyd, Louis’ choice is ‘Look After You’ by The Fray while Niall’s is Coldplay’s ‘Viva La Vida’. Liam prefers ‘Happy Birthday’ as it means he will open presents.",
  "In December 2011, Niall had braces fitted on his teeth. You’ll have to look very close to see them as they’re white ones.",
  "1D once said they would really love to collaborate with Bruno Mars. They told teen.com, “(He has) great songs, great stage presence, an unbelievable performer. His vocal is absolutely flawless.”",
  "All the boys used to live within 100 yards of each other in London. Harry and Louis, who are apparently the messiest members of the band, once shared a house!",
  "Zayn Malik was the first to leave the band. He left on the 25th March 2015.",
  "How tall are the One Direction boys? Niall Horan and Louis Tomlinson are both 5'8\", Harry Styles is 5'11\", Liam Payne is 5'10\"; and (former member) Zayn Malik is 5'9\".",
  "The One Direction boys prefer to sleep in their tour bus rather than a hotel when they're out on tour.",
  "Since going solo the boys have released songs with very similar titles to their One Direction"
];
